return {
    "norcalli/nvim-colorizer.lua",
    event = "BufRead",
    config = function()
        require("colorizer").setup({
            css = {
                RGB = true,
                RRGGBB = true,
                names = true,
                RRGGBBAA = true,
                rgb_fn = true,
                hsl_fn = true,
                css = true,
                css_fn = true,
                mode = "background",
                tailwind = true,
                sass = { enable = true },
                virtualtext = "■",
            },
            html = { mode = "background", tailwind = true, css = true, css_fn = true },
            javascript = { mode = "background", tailwind = true, css = true, css_fn = true },
            typescript = { mode = "background", tailwind = true, css = true, css_fn = true },
            jsx = { mode = "background", tailwind = true, css = true, css_fn = true },
            tsx = { mode = "background", tailwind = true, css = true, css_fn = true },
            sass = { mode = "background", sass = { enable = true } },
            scss = { mode = "background", sass = { enable = true } },
            svelte = { mode = "background", tailwind = true, css = true, css_fn = true },
            vue = { mode = "background", tailwind = true, css = true, css_fn = true },
            json = { mode = "background", RRGGBB = true, RGB = true, RRGGBBAA = true },
            yaml = { mode = "background", RRGGBB = true, RGB = true },
            markdown = { mode = "background", RRGGBB = true, RGB = true },
            php = { mode = "background", css = true, tailwind = true },
            ruby = { mode = "background", RRGGBB = true, RGB = true },
            xml = { mode = "background", RRGGBB = true, RGB = true },
            lua = { mode = "background", RRGGBB = true, RGB = true },
            dart = { mode = "background", RRGGBB = true, RGB = true },
            swift = { mode = "background", RRGGBB = true, RGB = true },
            ["*"] = {
                RGB = true,
                RRGGBB = true,
                names = false,
                RRGGBBAA = true,
                rgb_fn = false,
                hsl_fn = false,
                css = false,
                css_fn = false,
                mode = "background",
                tailwind = false,
                sass = { enable = false },
                virtualtext = "■",
            },
        })
    end,
}
